spring:
 datasource:
  url: jdbc:mysql://localhost:3306/schema?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
  username: root
  password: 3410043420
  driver-class-name: com.mysql.cj.jdbc.Driver
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true
ai:
 provider: siliconflow
 apiUrl: https://api.siliconflow.cn/v1/chat/completions
 apiKey: sk-qrugbdknhyutagdzmnwxyqllbuvudojhfbmwgtedqrljkxwn
 model: deepseek-ai/DeepSeek-V2.5

